import { createIndexer } from 'octothorpes'
import { insert, query, queryBoolean, queryArray } from '$lib/sparql.js'
import { instance } from '$env/static/private'

const indexer = createIndexer({
  insert,
  query,
  queryBoolean,
  queryArray,
  instance,
})

export const {
  handler,
  handleThorpe,
  handleMention,
  handleWebring,
  isHarmonizerAllowed,
  checkIndexingRateLimit,
  parseRequestBody,
  isURL,
  getAllMentioningUrls,
  getDomainForUrl,
  recentlyIndexed,
  extantTerm,
  extantPage,
  extantMember,
  extantThorpe,
  extantMention,
  extantBacklink,
  createBacklink,
  createOctothorpe,
  createTerm,
  createPage,
  createWebring,
  createWebringMember,
  deleteWebringMember,
  createMention,
  recordIndexing,
  recordProperty,
  recordTitle,
  recordDescription,
  recordImage,
  recordPostDate,
  recordUsage,
  recordCreation,
  resolveSubtype,
  checkIndexingPolicy,
  originEndorsesOrigin,
  checkReciprocalMention,
  checkEndorsement,
  webringMembers,
} = indexer
